### ISSUE TITLE
Schimbare logică login.php

### ISSUE THREAD

**Issue by madalink-ro** [RAISADR/p2#1]
Încearcă să schimbi puțin logica fișierului de login. 

Nu are sens să extragi o listă cu toți administratorii înainte de a avea niște date cu care să lucrezi.

Ți-aș propune să faci în felul următor:
- [ ] după apăsarea butonului de login sa verifici în baza de date dacă există un utilizator cu numele introdus `SELECT * FROM administrators WHERE username=$_POST['username']` 
- [ ] dacă există acel username verifici dacă parola din db este aceeași cu cea introdusă `$row['password']===$_POST['password']`
- [ ] dacă totul este bine, setezi sesiunile, altfel afișezi un mesaj de eroare

Problema logării doar cu ultimul rând din baza de date vine din acel `while` care suprascrie variabilele `$user` și `$pass` pentru fiecare rând existent în db.

**Comment by RAISADR** [comment]
Am incercat sa adaptez codul in functie de sfatul tau, insa tot nu reusesc sa fac interogarea corecta, din pacate.

**Comment by madalink-ro** [comment]
Ce erori primești? Ce anume nu îți iese?

Eu propun  să regândești toată pagina, nu să încerci să o adaptezi. Dacă tot nu îți iese, dimineață o sa vin cu un exemplu concret. 

Dar ideal ar fi "să te chinui" puțin înainte :)

**Comment by RAISADR** [comment]
In regula, maine dimineata asta aveam de gand sa fac, probabil ca voi incerca si cu o noua abordare de la 0. Multumesc, din nou pentru raspuns!

**Comment by RAISADR** [comment]
Momentan la solutia asta am ajuns, doar ca orice nume si parola furnizez, codul tot pe ramura 'else' intra. De asemenea , am incercat si o metoda cu verificarea si stocarea locala a username-ului , insa tot fara prea mare succes .

**Comment by madalink-ro** [comment]
Hello,

Din câte văd în statementul sql nu are spații după variabilele folosite. Încearcă ceva de genul:

`$sql="select * from administrator where username='$username' AND password='$password' limit 1";`

Desigur, poți concatena cu double quotes, dar dacă `$username` sau `$password` ar conține un spațiu, acesta ar fi considerat parte din statementul sql. Pentru ca statementul să fie corect ar trebui rescris așa:

` $sql="select * from administrator where username='".$username."' AND password='".$password."' limit 1";` 

Nu am făcut altceva decât să pun un single quote înainte și după variabile și să adaug un spațiu după acestea.

Pentru a verifica dacă statementul este corect, îl poți afișa în pagină cu `echo $sql;` - așa s-ar putea să îți dai seama dacă există o eroare de sintaxă sau alte probleme :)

Btw, te-ai descurcat foarte bine!

**Comment by RAISADR** [comment]
Hei ! 

Am reusit in cele din urma sa stabilizez codul si sa il fac sa functioneze :)) . M-au ajutat sfaturile tale in legatura cu abordarea unei tehnici putin diferite , dat fiind faptul ca fostul cod suprascria elemente in tabelul meu . Multumesc foarte mult pentru timp si pentru ajutor , as lasa +1 / like sau orice forma de multumire , unde se poate :)) .

**Comment by madalink-ro** [comment]
Haha, mă bucur că ți-am putut fi de ajutor! Mult succes pe viitor 😊
